# Generated by Django 5.2.3 on 2025-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(default='High Frequency Breakout', max_length=100)),
                ('closing_price', models.FloatField()),
                ('lot_size', models.IntegerField(default=15)),
                ('target', models.FloatField(default=500)),
                ('stoploss', models.FloatField(default=250)),
                ('trade_start', models.TimeField(default='09:15')),
                ('trade_end', models.TimeField(default='09:45')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
