# Generated by Django 5.2.3 on 2025-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeconfig',
            name='future_entry_direction',
            field=models.CharField(choices=[('BUY', 'Buy (Call Option)'), ('SELL', 'Sell (Put Option)')], default='BUY', max_length=4),
        ),
    ]
