# Generated by Django 5.2.3 on 2025-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_tradeconfig_future_entry_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('option_symbol', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=10)),
                ('strike_price', models.IntegerField()),
                ('pnl', models.FloatField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
