# Generated by Django 5.2.3 on 2025-06-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_tradelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='entry_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradelog',
            name='exit_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradelog',
            name='status',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradelog',
            name='strategy',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='strategy.tradeconfig'),
            preserve_default=False,
        ),
    ]
