# Generated by Django 5.2.6 on 2025-11-13 11:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelog',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Trade Log', 'verbose_name_plural': 'Trade Logs'},
        ),
        migrations.AddField(
            model_name='tradelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='dry_run',
            field=models.BooleanField(default=True, help_text='Whether this was a simulated trade'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Option expiry date', null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='futures_ltp_entry',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Futures LTP at entry', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='futures_ltp_exit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Futures LTP at exit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='strike',
            field=models.IntegerField(blank=True, help_text='Option strike price', null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='breakout_buffer',
            field=models.IntegerField(default=10, help_text='Breakout buffer points (recommended: 10 pts)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000'), help_text='Available capital for trading (recommended: ₹30,000)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='max_daily_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('600'), help_text='Maximum daily loss limit (recommended: 2% of capital = ₹600)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='min_stoploss_points',
            field=models.IntegerField(default=40, help_text='Minimum stoploss points (recommended: 40 pts)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='risk_per_trade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Risk per trade as percentage of capital (recommended: 1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rsi_buy_max',
            field=models.IntegerField(default=70, help_text='RSI maximum for BUY (recommended: 70)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rsi_buy_min',
            field=models.IntegerField(default=55, help_text='RSI minimum for BUY (recommended: 55)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rsi_sell_max',
            field=models.IntegerField(default=45, help_text='RSI maximum for SELL (recommended: 45)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='rsi_sell_min',
            field=models.IntegerField(default=30, help_text='RSI minimum for SELL (recommended: 30)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='square_off_time',
            field=models.TimeField(default='14:45:00', help_text='Square-off time (recommended: 2:45 PM)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='trade_end_time',
            field=models.TimeField(default='10:30:00', help_text='Trading window end (recommended: 10:30 AM)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='trade_start_time',
            field=models.TimeField(default='09:30:00', help_text='Trading window start (recommended: 9:30 AM)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='volume_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Volume breakout multiplier (recommended: 1.5x avg)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_trades', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_side',
            field=models.CharField(help_text='BUY_CE, BUY_PE, BUY, SELL', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_symbol',
            field=models.CharField(help_text='Option symbol (e.g., BANKNIFTY14NOV25C58500)', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_trades', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('TARGET', 'Target Hit'), ('STOPLOSS', 'Stoploss Hit'), ('TIME', 'Time Exit (Square-off)'), ('MARKET_CLOSE', 'Market Close'), ('MANUAL', 'Manual Exit'), ('TRAILING', 'Trailing Stoploss')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='signal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='trading.signal'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='stoploss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['-entry_time'], name='trading_tra_entry_t_23a5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['is_open'], name='trading_tra_is_open_c86df7_idx'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['strategy', '-entry_time'], name='trading_tra_strateg_f52538_idx'),
        ),
    ]
