# Generated by Django 5.0.1 on 2025-11-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_option_fields_to_tradelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='yesterday_closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Yesterday's futures closing price (used for ATM strike selection)", max_digits=10, null=True),
        ),
    ]
