# Generated by Django 5.0.1 on 2025-11-19 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_add_yesterday_closing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='num_lots',
            field=models.IntegerField(default=1, help_text='Number of lots to trade (start with 1, increase as needed)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
