# Generated by Django 5.0.1 on 2025-11-19 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_add_num_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='trade_cooldown_minutes',
            field=models.IntegerField(default=5, help_text='Cooldown period in minutes after trade exit before allowing new entry (recommended: 5 minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
