# Generated by Django 5.0.1 on 2025-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_trade_cooldown'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeikinAshiCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Trading symbol', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Candle timestamp (end time)')),
                ('original_open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ha_open', models.DecimalField(decimal_places=2, help_text='HA_Open = (prev_HA_Open + prev_HA_Close) / 2', max_digits=10)),
                ('ha_close', models.DecimalField(decimal_places=2, help_text='HA_Close = (O + H + L + C) / 4', max_digits=10)),
                ('ha_high', models.DecimalField(decimal_places=2, help_text='HA_High = max(H, HA_Open, HA_Close)', max_digits=10)),
                ('ha_low', models.DecimalField(decimal_places=2, help_text='HA_Low = min(L, HA_Open, HA_Close)', max_digits=10)),
                ('color', models.CharField(choices=[('green', 'Green (Bullish)'), ('red', 'Red (Bearish)')], help_text='green if HA_Close > HA_Open, else red', max_length=10)),
                ('trend', models.CharField(choices=[('uptrend_start', 'Uptrend Start'), ('downtrend_start', 'Downtrend Start'), ('uptrend_continue', 'Uptrend Continue'), ('downtrend_continue', 'Downtrend Continue'), ('neutral', 'Neutral')], default='neutral', help_text='Trend direction and reversal status', max_length=20)),
                ('volume', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heikin-Ashi Candle',
                'verbose_name_plural': 'Heikin-Ashi Candles',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='trading_hei_symbol_22d01c_idx'), models.Index(fields=['symbol', 'color'], name='trading_hei_symbol_a6805d_idx'), models.Index(fields=['symbol', 'trend'], name='trading_hei_symbol_b7f9fc_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
