# Generated by Django 5.0.1 on 2025-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_add_heikin_ashi_candle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('TARGET', 'Target Hit'), ('STOPLOSS', 'Stoploss Hit'), ('TIME', 'Time Exit (Square-off)'), ('MARKET_CLOSE', 'Market Close'), ('MANUAL', 'Manual Exit'), ('TRAILING', 'Trailing Stoploss'), ('FUTURES_TARGET', 'Futures Target Hit'), ('OPTION_TARGET', 'Option Target Hit'), ('TREND_REVERSAL', 'HA Trend Reversal')], max_length=20, null=True),
        ),
    ]
