# Generated by Django 5.0.1 on 2025-12-01 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_add_exit_reason_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='base_daily_target_per_lot',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Base daily profit target per lot (default: ₹1000 for 35 quantity)', max_digits=12),
        ),
        migrations.AddField(
            model_name='strategy',
            name='daily_stop_loss_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Daily stop-loss as factor of daily target (default: 0.5 = 50%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='strategy',
            name='option_target_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Option profit target as percentage (default: 0.15 = 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='strategy',
            name='per_trade_profit_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Per-trade profit target in rupees (default: ₹500)', max_digits=12),
        ),
        migrations.AddField(
            model_name='strategy',
            name='square_off_time_ha',
            field=models.TimeField(default='15:20:00', help_text='Square-off time for Heikin Ashi strategy (default: 15:20 = 3:20 PM)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stoploss_futures_points',
            field=models.IntegerField(default=30, help_text='Futures stop-loss in points (default: 30 points)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stoploss_option_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Option stop-loss as percentage (default: 0.30 = 30%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='strategy',
            name='target_points',
            field=models.IntegerField(default=60, help_text='Futures profit target in points (default: 60 points)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trade_end_time_ha',
            field=models.TimeField(default='15:30:00', help_text='Trading end time for Heikin Ashi strategy (default: 15:30 = 3:30 PM)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trade_start_time_ha',
            field=models.TimeField(default='09:15:00', help_text='Trading start time for Heikin Ashi strategy (default: 09:15 = 9:15 AM)'),
        ),
    ]
