# Generated by Django 5.0.1 on 2025-12-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_add_heikin_trailing_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('TARGET', 'Target Hit'), ('STOPLOSS', 'Stoploss Hit'), ('TIME', 'Time Exit (Square-off)'), ('MARKET_CLOSE', 'Market Close'), ('MANUAL', 'Manual Exit'), ('TRAILING', 'Trailing Stoploss'), ('PROFIT_TARGET', 'Per-trade Profit Target Hit'), ('FUTURES_TARGET', 'Futures Target Hit'), ('OPTION_TARGET', 'Option Target Hit'), ('TREND_REVERSAL', 'HA Trend Reversal'), ('DAILY_TARGET', 'Daily Profit Target Hit'), ('DAILY_STOP', 'Daily Stop-loss Hit'), ('DAILY_HALT', 'Daily Trading Halt')], max_length=20, null=True),
        ),
    ]
