"""
Django models for BankNifty Momentum Breakout Strategy
"""
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal


class Strategy(models.Model):
    """Main strategy configuration"""
    name = models.CharField(max_length=100, default="BankNifty Momentum Breakout")
    enabled = models.BooleanField(default=False, help_text="Enable/disable strategy (kill switch)")
    
    # Risk parameters
    capital = models.DecimalField(
        max_digits=12, decimal_places=2, default=Decimal('30000'),
        help_text="Available capital for trading (recommended: ₹30,000)"
    )
    risk_per_trade_pct = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal('1.00'),
        validators=[MinValueValidator(0.1), MaxValueValidator(5.0)],
        help_text="Risk per trade as percentage of capital (recommended: 1%)"
    )
    max_daily_loss = models.DecimalField(
        max_digits=12, decimal_places=2, default=Decimal('600'),
        help_text="Maximum daily loss limit (recommended: 2% of capital = ₹600)"
    )
    max_concurrent_trades = models.IntegerField(
        default=1, validators=[MinValueValidator(1)],
        help_text="Maximum concurrent open positions"
    )
    
    # Trading parameters
    lot_size = models.IntegerField(default=35, help_text="Lot size for BankNifty options")
    tick_value = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('1.00'),
        help_text="Point value per lot (default: 1 for options)"
    )
    breakout_buffer = models.IntegerField(
        default=10, help_text="Breakout buffer points (recommended: 10 pts)"
    )
    min_stoploss_points = models.IntegerField(
        default=40, help_text="Minimum stoploss points (recommended: 40 pts)"
    )
    stoploss_range_multiplier = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal('0.6'),
        help_text="Stoploss as multiplier of range (default: 0.6)"
    )
    target_multiplier = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal('1.5'),
        help_text="Target as multiplier of stoploss (default: 1.5)"
    )
    
    # Momentum parameters
    volume_multiplier = models.DecimalField(
        max_digits=5, decimal_places=2, default=Decimal('1.5'),
        help_text="Volume breakout multiplier (recommended: 1.5x avg)"
    )
    ema_fast = models.IntegerField(default=20, help_text="Fast EMA period")
    ema_slow = models.IntegerField(default=50, help_text="Slow EMA period")
    rsi_period = models.IntegerField(default=14, help_text="RSI period")
    rsi_buy_min = models.IntegerField(default=55, help_text="RSI minimum for BUY (recommended: 55)")
    rsi_buy_max = models.IntegerField(default=70, help_text="RSI maximum for BUY (recommended: 70)")
    rsi_sell_min = models.IntegerField(default=30, help_text="RSI minimum for SELL (recommended: 30)")
    rsi_sell_max = models.IntegerField(default=45, help_text="RSI maximum for SELL (recommended: 45)")
    
    # Time windows
    range_start_time = models.TimeField(default="09:15:00", help_text="Range detection start (9:15 AM)")
    range_end_time = models.TimeField(default="09:30:00", help_text="Range detection end (9:30 AM)")
    trade_start_time = models.TimeField(default="09:30:00", help_text="Trading window start (recommended: 9:30 AM)")
    trade_end_time = models.TimeField(default="10:30:00", help_text="Trading window end (recommended: 10:30 AM)")
    square_off_time = models.TimeField(default="14:45:00", help_text="Square-off time (recommended: 2:45 PM)")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Strategy"
        verbose_name_plural = "Strategies"
        ordering = ['-created_at']
    
    def __str__(self):
        status = "ENABLED" if self.enabled else "DISABLED"
        return f"{self.name} - {status}"


class Signal(models.Model):
    """Trading signals generated by strategy"""
    SIGNAL_TYPES = [
        ('BUY', 'Buy Signal'),
        ('SELL', 'Sell Signal'),
    ]
    
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, related_name='signals')
    signal_type = models.CharField(max_length=4, choices=SIGNAL_TYPES)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    # Range data
    first_high = models.DecimalField(max_digits=10, decimal_places=2)
    first_low = models.DecimalField(max_digits=10, decimal_places=2)
    range_value = models.DecimalField(max_digits=10, decimal_places=2)
    
    # Breakout data
    breakout_price = models.DecimalField(max_digits=10, decimal_places=2)
    breakout_volume = models.BigIntegerField()
    avg_volume = models.BigIntegerField()
    
    # Momentum data
    ema_fast_value = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    ema_slow_value = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    rsi_value = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    momentum_score = models.IntegerField(default=0, help_text="Momentum score (0-4)")
    
    # Strike selection
    spot_price = models.DecimalField(max_digits=10, decimal_places=2)
    selected_strike = models.IntegerField()
    selected_symbol = models.CharField(max_length=50)
    expiry_date = models.DateField()
    
    # Risk calculation
    stoploss_points = models.IntegerField()
    target_points = models.IntegerField()
    calculated_qty = models.IntegerField()
    
    # Status
    executed = models.BooleanField(default=False)
    execution_reason = models.TextField(blank=True, help_text="Why signal was executed or rejected")
    
    class Meta:
        ordering = ['-timestamp']
    
    def __str__(self):
        return f"{self.signal_type} @ {self.breakout_price} - {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}"


class Order(models.Model):
    """Order records"""
    ORDER_STATUS = [
        ('PENDING', 'Pending'),
        ('SUBMITTED', 'Submitted'),
        ('FILLED', 'Filled'),
        ('PARTIALLY_FILLED', 'Partially Filled'),
        ('CANCELLED', 'Cancelled'),
        ('REJECTED', 'Rejected'),
    ]
    
    signal = models.ForeignKey(Signal, on_delete=models.CASCADE, related_name='orders', null=True, blank=True)
    order_id = models.CharField(max_length=100, unique=True, help_text="Broker order ID")
    symbol = models.CharField(max_length=50)
    side = models.CharField(max_length=4, choices=[('BUY', 'Buy'), ('SELL', 'Sell')])
    quantity = models.IntegerField()
    order_type = models.CharField(max_length=20, default="MARKET")
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='PENDING')
    
    # Prices
    limit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    filled_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    filled_at = models.DateTimeField(null=True, blank=True)
    
    # Execution details
    dry_run = models.BooleanField(default=True)
    execution_adapter = models.CharField(max_length=50, default="MockAdapter")
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.side} {self.quantity} {self.symbol} @ {self.filled_price or 'PENDING'}"


class TradeLog(models.Model):
    """Complete trade log with entry/exit"""
    EXIT_REASONS = [
        ('TARGET', 'Target Hit'),
        ('STOPLOSS', 'Stoploss Hit'),
        ('TIME', 'Time Exit (Square-off)'),
        ('MARKET_CLOSE', 'Market Close'),
        ('MANUAL', 'Manual Exit'),
        ('TRAILING', 'Trailing Stoploss'),
    ]
    
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, related_name='trades')
    signal = models.OneToOneField(Signal, on_delete=models.CASCADE, related_name='trade', null=True, blank=True)
    entry_order = models.ForeignKey(Order, on_delete=models.SET_NULL, related_name='entry_trades', null=True, blank=True)
    exit_order = models.ForeignKey(Order, on_delete=models.SET_NULL, related_name='exit_trades', null=True, blank=True)
    
    # Entry details
    entry_time = models.DateTimeField()
    entry_price = models.DecimalField(max_digits=10, decimal_places=2)
    entry_symbol = models.CharField(max_length=50, help_text="Option symbol (e.g., BANKNIFTY14NOV25C58500)")
    entry_side = models.CharField(max_length=10, help_text="BUY_CE, BUY_PE, BUY, SELL")
    entry_quantity = models.IntegerField(default=1)
    
    # Option-specific fields (for options trading)
    strike = models.IntegerField(null=True, blank=True, help_text="Option strike price")
    expiry_date = models.DateField(null=True, blank=True, help_text="Option expiry date")
    futures_ltp_entry = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, 
                                            help_text="Futures LTP at entry")
    futures_ltp_exit = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                          help_text="Futures LTP at exit")
    
    # Exit details
    exit_time = models.DateTimeField(null=True, blank=True)
    exit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    exit_reason = models.CharField(max_length=20, choices=EXIT_REASONS, null=True, blank=True)
    
    # P&L
    stoploss_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    target_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    pnl_points = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    pnl_value = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    commission = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    slippage_estimate = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    
    # Trailing stoploss
    trailing_stoploss_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    breakeven_triggered = models.BooleanField(default=False)
    
    # Status
    is_open = models.BooleanField(default=True)
    dry_run = models.BooleanField(default=True, help_text="Whether this was a simulated trade")
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    
    class Meta:
        ordering = ['-entry_time']
        verbose_name = "Trade Log"
        verbose_name_plural = "Trade Logs"
        indexes = [
            models.Index(fields=['-entry_time']),
            models.Index(fields=['is_open']),
            models.Index(fields=['strategy', '-entry_time']),
        ]
    
    def __str__(self):
        status = "OPEN" if self.is_open else "CLOSED"
        pnl = f"₹{self.pnl_value:,.2f}" if self.pnl_value is not None else "N/A"
        mode = "[DRY-RUN]" if self.dry_run else "[LIVE]"
        return f"{mode} {self.entry_symbol} {self.entry_side} - {status} - {pnl}"
    
    @property
    def is_profitable(self):
        if self.pnl_value is None:
            return None
        return self.pnl_value > 0
    
    @property
    def duration_minutes(self):
        """Calculate trade duration in minutes"""
        if not self.exit_time:
            return None
        delta = self.exit_time - self.entry_time
        return int(delta.total_seconds() / 60)
    
    @property
    def pnl_percentage(self):
        """Calculate P&L as percentage of entry price"""
        if not self.pnl_points or not self.entry_price:
            return None
        return (self.pnl_points / self.entry_price) * 100


class DailyStats(models.Model):
    """Daily trading statistics"""
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, related_name='daily_stats')
    date = models.DateField(unique=True)
    
    # Trade counts
    total_trades = models.IntegerField(default=0)
    winning_trades = models.IntegerField(default=0)
    losing_trades = models.IntegerField(default=0)
    
    # P&L
    total_pnl = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    gross_profit = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    gross_loss = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    
    # Metrics
    win_rate = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
    avg_win = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    avg_loss = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    profit_factor = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    
    # Risk metrics
    max_drawdown = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    max_drawdown_time = models.DateTimeField(null=True, blank=True)
    
    # Other
    total_commission = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    total_slippage = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-date']
        unique_together = ['strategy', 'date']
    
    def __str__(self):
        return f"{self.date} - Trades: {self.total_trades}, PnL: ₹{self.total_pnl}, Win Rate: {self.win_rate}%"

