from alice_blue import AliceBlue, LiveFeedType
import time

username = '1293756'
password = 'Ashok@123'
access_token = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyam9lOFVScGxZU3FTcDB3RDNVemVBQkgxYkpmOE4wSDRDMGVVSWhXUVAwIn0.eyJleHAiOjE3NTUxODQwMTIsImlhdCI6MTc1MDQ4MDkwNCwianRpIjoiZDU4MzY2MzctODQ2My00ZWRiLWFkNDItYWU3YWU0OGU0ZWQ4IiwiaXNzIjoiaHR0cHM6Ly9pZGFhcy5hbGljZWJsdWVvbmxpbmUuY29tL2lkYWFzL3JlYWxtcy9BbGljZUJsdWUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNTg5MzlkNjMtNmYwNi00ZDA3LTgxNDMtYTY0MGQwYTY2OTNjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWxpY2Uta2IiLCJzaWQiOiI1YTBjMDY1NS0zZjljLTQ3MTUtYjZlMy05Y2UzYTk4MThjMGIiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDozMDAyIiwiaHR0cDovL2xvY2FsaG9zdDo1MDUwIiwiaHR0cDovL2xvY2FsaG9zdDo5OTQzIiwiaHR0cDovL2xvY2FsaG9zdDo5MDAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtYWxpY2VibHVla2IiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFsaWNlLWtiIjp7InJvbGVzIjpbIkdVRVNUX1VTRVIiLCJBQ1RJVkVfVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIG9wZW5pZCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJ1Y2MiOiIxMjkzNzU2IiwiY2xpZW50Um9sZSI6WyJHVUVTVF9VU0VSIiwiQUNUSVZFX1VTRVIiXSwibmFtZSI6IkFTSE9LS1VNQVIiLCJtb2JpbGUiOiI3MzU4MTY4OTE5IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiMTI5Mzc1NiIsImdpdmVuX25hbWUiOiJBU0hPS0tVTUFSIiwiZW1haWwiOiJhc2hva3lsY2Mua3VtYXJAZ21haWwuY29tIn0.J4ZVoTLPB2P9aR08t-9tT2LD38QOe1_ZPVz2pb6QOicCeaSjnrABMc5TG8oQkMmtWZ6uX_zJ4vcyIJje8JIKfsJtKEZOyub7IKgmbZI-oUu6AkB7Oxb0W6dBsDLuFgDZPgchCRBVjEqGyw-7wzadNrAKcChQTax1d9tNBwvPWoZs4TbCJrHGWsBQD_E8H0c_IOM6QCmG09vNts-p5Usj17Gj-Ik4CL-fruE3esUyEf4R0Y2BoXobQlyN52HaLE-NMpFtQOzJRt89hb7Q6C0AvOF20F0wJYH8FvqPyYxT6IipjSz1LmgjF3qfCDnJ0GyH3X3rnFw8qSwGruSC2mK4hQ'

alice = AliceBlue(
    username=username,
    access_token=access_token,
    exchanges=['NSE', 'NFO']
)

def event_handler_quote_update(ticks):
    print(ticks)

def open_callback():
    global socket_opened
    socket_opened = True
    print("WebSocket opened")

socket_opened = False
alice.start_websocket(event_handler_quote_update, open_callback, run_in_background=True)

while not socket_opened:
    time.sleep(1)

instrument = alice.get_instrument_by_symbol('NFO', 'BANKNIFTY31JUL25C55700')
alice.subscribe([instrument], LiveFeedType.MARKET_DATA)

while True:
    time.sleep(1)